name: trufflehog

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  scan:
    uses: cboone/gh-actions/.github/workflows/scan-for-secrets.yml@3c9adb5a8b166444d3c0e3fe606d55f0dc7ac726 # v5.0.0
    with:
      tool: trufflehog
